CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT roles_type_check CHECK (
        type IN (
            'GLOBAL_ADMIN',
            'PROJECT_ORGANIZATION_ADMIN',
            'CONTROL_ADMIN',
            'REQUEST_INITIATOR',
            'WORK_EXECUTOR'
        )
    )
);

CREATE TABLE users_roles (
    user_id INT NOT NULL,
    role_id INT NOT NULL,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_users_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_users_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON DELETE RESTRICT
);

CREATE TABLE work_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);