CREATE TABLE requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    goal TEXT,
    expected_result TEXT NOT NULL,
    desired_deadline DATE,
    material_url TEXT,
    clarification TEXT,
    status request_status_type NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE TABLE tasks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id INT NOT NULL,
    stage_id INT,
    sprint_id INT,
    request_id INT UNIQUE,

    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,

    work_type_id INT NOT NULL,
    priority task_priority_type NOT NULL DEFAULT 'MEDIUM',
    status task_status_type NOT NULL DEFAULT 'TO_DO',

    assignee_id INT,
    created_by_user_id INT,

    deadline DATE,
    completed_at TIMESTAMP,
    closed_at TIMESTAMP,

    result_description TEXT,
    result_url TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    FOREIGN KEY (project_id, stage_id)
        REFERENCES project_stages(project_id, id),

    FOREIGN KEY (project_id, sprint_id)
        REFERENCES sprints(project_id, id),

    FOREIGN KEY (request_id)
        REFERENCES requests(id)
        ON DELETE SET NULL,

    FOREIGN KEY (work_type_id)
        REFERENCES work_types(id)
        ON DELETE RESTRICT,

    FOREIGN KEY (assignee_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    FOREIGN KEY (created_by_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

