CREATE TABLE task_comments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id INT NOT NULL,
    author_id INT,
    comment_type task_comment_type NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (task_id)
        REFERENCES tasks(id)
        ON DELETE CASCADE,

    FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE TABLE user_action_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INT,
    action_type user_action_type NOT NULL,
    object_type action_object_type NOT NULL,
    object_id INT,
    object_name VARCHAR(150),
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (actor_user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);